### ISSUE TITLE
Changes not showing up and link not working

### ISSUE THREAD

**Issue by Kyle-Jackson** [Kyle-Jackson/dsn1675-assignment-1#1]
@thomasjbradley

After I save my changes that I made in Atom they aren't showing up anymore in GitHub and it says there are no changes to commit even though I've made a lot of changes. My link to my website also isn't working even though I'm putting the address in properly. I was wondering if you knew what the problem might be and how I can go about fixing it.

Thanks,
Kyle

**Comment by thomasjbradley** [comment]
Go to the GitHub application on your computer, then go to the “Repository” menu and press “Open in Finder”. Compare that location to the one where you’ve been saving the code, they’re most likely different.

Also, the design, content, & assets folder should not be on GitHub.

**Comment by Kyle-Jackson** [comment]
Thanks @thomasjbradley, that solved my issue.
